# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0002_auto_20171025_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='group',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='user',
            new_name='member_id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='date_joined',
        ),
    ]
