# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0003_auto_20171102_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='admin_name',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='group_name',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='member_id',
            new_name='member',
        ),
    ]
