# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-25 22:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MS', '0005_auto_20171103_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
                ('messageType', models.CharField(choices=[('NO', 'Notification'), ('GI', 'Group_invitaion'), ('MI', 'Meeting_invitation'), ('DF', 'Default')], default='DF', max_length=2)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_dm', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_dm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
