# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-26 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0006_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='messageType',
        ),
    ]
