# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-30 05:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MS', '0009_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('RJ', 'Rejected'), ('NO', 'No response')], default='NO', max_length=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mi', to='MS.Group')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mi', to='MS.Meeting')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_mi', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_mi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
